//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodMaterial.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Sale = new HashSet<Sale>();
        }
    
        public int Id { get; set; }
        public string Fullname { get; set; }
        public System.DateTime DateOfRegistration { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> WhenToRemind { get; set; }
        public string WhatToRemind { get; set; }
    
        public virtual ICollection<Sale> Sale { get; set; }
    }
}
